In [1]:
#Question No 1

In [2]:
input_Value=input("Enter the product Name : ")

Enter the product Name : Guitar

In [3]:
#Question No 2---------------------Amazon product details scrapping

In [4]:
from selenium import webdriver
import time
from selenium.common.exceptions import NoSuchElementException
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By
import pandas as pd

In [5]:
driver=webdriver.Chrome()
driver.get("https://www.amazon.in/")

In [6]:
search_product=driver.find_element(By.XPATH,'/html/body/div[1]/header/div/div[1]/div[2]/div/form/div[2]/div[1]/input')
search_product.send_keys(input_Value)

In [7]:
search=driver.find_element(By.XPATH,'/html/body/div[1]/header/div/div[1]/div[2]/div/form/div[3]/div/span/input')
search.click()

In [8]:
#lets scrape all the product url 

product_url=[]
start=0
end=3
for page in range(start,end):
    url=driver.find_elements(By.XPATH,'//a[@class="a-link-normal s-underline-text s-underline-link-text s-link-style a-text-normal"]')
    for i in url:
        product_url.append(i.get_attribute('href'))
    next_button=driver.find_element(By.XPATH,'//a[@class="s-pagination-item s-pagination-next s-pagination-button s-pagination-separator"]')
    next_button.click()
    time.sleep(3)

In [10]:
#Lets scrap the brand name
for url in product_url:
    driver.get(url)
    time.sleep(3)
    try:
        brand=driver.find_element(By.XPATH,'//*[@id="productOverview_feature_div"]/div/table/tbody/tr[1]/td[2]/span')
        Brand.append(brand.text)
    except NoSuchElementException:
        Brand.append('-')

In [12]:
#lets Scrape the price

for url in product_url:
    driver.get(url)
    time.sleep(3)
    try:
        price=driver.find_element(By.XPATH,'//span[@class="a-price aok-align-center reinventPricePriceToPayMargin priceToPay"]')
        Price.append(price.text)
    except NoSuchElementException:
        Price.append('-')
        
        
        
#Lets scrape the return 

for url in product_url:
    driver.get(url)
    time.sleep(3)
    try:
        returns=driver.find_element(By.XPATH,'//div[@class="a-column a-span12 a-text-center icon-container scrollable-container celwidget"]/span[1]/div[2]/span')
        Return.append(returns.text)
    except NoSuchElementException:
        Return.append('-')
        
        
        
        
#lets check the delivery date


for url in product_url:
    driver.get(url)
    time.sleep(3)
    try:
        delivery=driver.find_element(By.XPATH,'//div[@class="a-spacing-base"]/span[1]/span[1]')
        Expected_delivery.append(delivery.text)
    except NoSuchElementException:
        Expected_delivery.append('-')

In [13]:
len(Expected_delivery)

174

In [14]:
len(Return)

174

In [15]:
len(Price)

174

In [16]:
len(Brand)

174

In [17]:
len(product_url)

174

In [18]:
#lets prepare the table using DataFrame
df=pd.DataFrame({'Product URL':product_url,'Brand':Brand,'Price of Product':Price,'Return/Exchange':Return,'Expected Delivery':Expected_delivery})
df

,Product URL,Brand,Price of Product,Return/Exchange,Expected Delivery
0,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...,Medellin,"₹2,499",7 days Replacement,"Friday, 11 August"
1,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...,Kadence,"₹4,999",7 days Replacement,"Friday, 11 August"
2,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...,Medellin,"₹2,499",7 days Replacement,"Friday, 11 August"
3,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...,Medellin,"₹2,499",7 days Replacement,"Friday, 11 August"
4,https://www.amazon.in/Juarez-Acoustic-Cutaway-...,JUAREZ,"₹1,999",7 days Replacement,"Sunday, 13 August"
...,...,...,...,...,...
169,https://www.amazon.in/Kadence-Slowhand-Premium...,Kadence,"₹8,999",7 days Replacement,"Friday, 11 August"
170,https://www.amazon.in/Traveler-Guitar-Vaibrant...,Traveler Guitar,"₹1,13,897",-,6 - 7 September
171,https://www.amazon.in/Juarez-JRZ-ST01-6-String...,JUAREZ,"₹5,749",7 days Replacement,"Sunday, 13 August"
172,https://www.amazon.in/Ibanez-V50NJP-VS-Acousti...,Ibanez,"₹9,212\n40",7 days Replacement,"Wednesday, 16 August"
173,https://www.amazon.in/Fender-String-Cutaway-Ac...,Fender,"₹7,400",7 days Replacement,"Wednesday, 16 August"

In [ ]:
csv_data = df.to_csv(index=False)

print(csv_data)

In [19]:
#Question  #3-----------Google images


Search_pic=input("Enter the pic name : ")
Search_pic

Enter the pic name : Cakes

'Cakes'

In [20]:
driver=webdriver.Chrome()
driver.get("https://images.google.com/")

In [21]:
image_search=driver.find_element(By.XPATH,'/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/textarea')
image_search.send_keys(Search_pic)

In [22]:
Search_button=driver.find_element(By.XPATH,'/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/button')
Search_button.click()

In [23]:
import requests

In [25]:
#Lets do the scrolling

for _ in range(10):
    driver.execute_script('window.scrollBy(0,100)')
    
images=driver.find_elements(By.XPATH,'//img[@class="rg_i Q4LuWd"]')


image_urls=[]
image_data=[]

for image in images:
    source=image.get_attribute('src')
    if source is not None:
        if(source[0:4] == 'http'):
            image_urls.append(source)
            
            
            
#lets download the image
for i in range(len(image_urls)):
    if i>10:
        breakBy.XPATH,
    print("Downloading {0} and {1} images ".format(i,10))
    response=requests.get(image_urls[i])
    file=open(r"D:\Data Science\Internship\Exception_handling_Selenium"+str(i)+".jpg","wb")
    file.write(response.content)

Downloading 0 and 10 images
Downloading 1 and 10 images
Downloading 2 and 10 images
Downloading 3 and 10 images
Downloading 4 and 10 images
Downloading 5 and 10 images
Downloading 6 and 10 images
Downloading 7 and 10 images
Downloading 8 and 10 images
Downloading 9 and 10 images
Downloading 10 and 10 images

NameError: name 'breakBy' is not defined

In [26]:
#Question No 5----------Lattitude and Longitude


driver=webdriver.Chrome()
driver.get("https://www.google.com/maps")

In [29]:
City=input("Enter the city name :")
City

Enter the city name :Singanamane

'Singanamane'

In [30]:
Search_City=driver.find_element(By.XPATH,'/html/body/div[3]/div[8]/div[3]/div[1]/div[1]/div/div[2]/form/input')
Search_City.send_keys(City)

In [32]:
Search_Button=driver.find_element(By.XPATH,'/html/body/div[3]/div[8]/div[3]/div[1]/div[1]/div/div[2]/div[1]/button')
Search_Button.click()

In [34]:
import re

In [35]:
url_string=driver.current_url
print("URL Extracted :",url_string)
lattitude_Longitude=re.findall(r'@(.*)data',url_string)
print(lattitude_Longitude)

URL Extracted : https://www.google.com/maps/place/Singanamane,+Thavaraghatta,+Karnataka+577115/@13.7173731,75.6303012,16z/data=!3m1!4b1!4m6!3m5!1s0x3bbb0376e3858a73:0xd8f96d22617b2b1c!8m2!3d13.7178139!4d75.6360837!16s%2Fm%2F05zl7br?entry=ttu
['13.7173731,75.6303012,16z/']

In [36]:
text = ','.join(lattitude_Longitude)

Latitude=text.split(',')[0]

print("Latitude of",City,'is :',Latitude)

Longitude=text.split(',')[1]

print('Longitude of',City,"is :", Longitude)

Latitude of Singanamane is : 13.7173731
Longitude of Singanamane is : 75.6303012

In [37]:
#Question NO6----------------Digit in  best gaming laptop

In [38]:
driver=webdriver.Chrome()
driver.get("https://www.digit.in/")

In [39]:
search_laptop=driver.find_element(By.XPATH,'/html/body/div[2]/div/ul/li[2]/span')
search_laptop.click()

In [40]:
search_best=driver.find_element(By.XPATH,'/html/body/div[2]/div/ul/li[2]/div[2]/div/div[1]/span[4]')
search_best.click()

In [41]:
click_best_gaming=driver.find_element(By.XPATH,'/html/body/div[2]/div/ul/li[2]/div[2]/div/div[5]/div/div[2]/a/div')
click_best_gaming.click()

In [42]:
laptop_name=[]

In [43]:
laptop_Name=driver.find_elements(By.XPATH,'//div[@class="TopNumbeHeading"]/div/span[2]/h3')
for i in laptop_Name:
    title11=i.text
    laptop_name.append(title11)

In [44]:
#lets scrap the OS

Operating_system=[]


OS=driver.find_elements(By.XPATH,'//div[@class="Spcs-details"]/table/tbody/tr[4]/td[3]')
for i in OS:
    OS1=i.text
    Operating_system.append(OS1)

In [45]:
#Lets scrape the Processor

Processor=[]

pro=driver.find_elements(By.XPATH,'//div[@class="Spcs-details"]/table/tbody/tr[2]/td[3]')
for i in pro:
    pro1=i.text
    Processor.append(pro1)

In [46]:
#Lets Scrape the display

Display=[]

Dis=driver.find_elements(By.XPATH,'//div[@class="Spcs-details"]/table/tbody/tr[3]/td[3]')
for i in Dis:
    Dis1=i.text
    Display.append(Dis1)

In [47]:
#lets scrape the price

Price1=[]

Pr=driver.find_elements(By.XPATH,'//div[@class="Spcs-details"]/table/tbody/tr[8]/td[3]')
for i in Pr:
    Pr1=i.text
    Price1.append(Pr1)

In [48]:
df3=pd.DataFrame({'Laptop Name':laptop_name,'Operating System':Operating_system,'Processor':Processor,'Display':Display, 'Price' : Price1 })
df3

,Laptop Name,Operating System,Processor,Display,Price
0,HP OMEN 17 (2023),Windows 11 Home,13th Gen Intel Core i7-13700HX 16 core process...,"17.3″ (2560 x 1440) screen, 165 Hz refresh rate","₹ 269,777"
1,MSI Titan GT77 12UHS,Windows 11 Home,12th Gen Intel Core i9-12900HX 16 core process...,"17.3″ (3840 x 2160) screen, 120 Hz refresh rate","₹ 499,990"
2,Lenovo Legion 5i Pro,Windows 11 Home,12th Gen Intel Core i7-12700H 14 core processo...,16″ (2560 x 1600) screen,"₹ 179,990"
3,ASUS ROG Strix Scar 18 2023,Windows 11 Home,13th Gen Intel Core i9-13980HX 24 core process...,"18″ (1920 x 1200) screen, 165 Hz refresh rate","₹ 279,990"
4,Acer Predator Helios Neo 16,Windows 11 Home,13th Gen Intel Core i7-13700HX processor,"16″ (2560 x 1600) screen, 165 Hz refresh rate","₹ 149,990"
5,ASUS ROG Zephyrus G14,Windows 11 Home,AMD Ryzen 9-6900HS 8 core processor with 4.9 G...,"14″ (1920 x 1200) screen, 144 Hz refresh rate","₹ 156,990"
6,MSI Cyborg 15,Windows 11 Home,12th Gen Intel Core i7-12650H 10 core processo...,"15.6″ (1920 x 1080) screen, 144 Hz refresh rate","₹ 125,000"

In [49]:
#Question No 8 ----500 Comments from Youtube


driver=webdriver.Chrome()
driver.get("https://www.youtube.com/")

In [50]:
#lets serach the content
search_content=driver.find_element(By.XPATH,'/html/body/ytd-app/div[1]/div/ytd-masthead/div[4]/div[2]/ytd-searchbox/form/div[1]/div[1]/input')
search_content.send_keys('Carry Minati')

In [51]:
#lets click the search 

Search_button=driver.find_element(By.XPATH,'/html/body/ytd-app/div[1]/div/ytd-masthead/div[4]/div[2]/ytd-searchbox/button')
Search_button.click()

In [52]:
#lets click on the video

Click=driver.find_element(By.XPATH,'/html/body/ytd-app/div[1]/ytd-page-manager/ytd-search/div[1]/ytd-two-column-search-results-renderer/div/ytd-section-list-renderer/div[2]/ytd-item-section-renderer/div[3]/ytd-shelf-renderer[1]/div[1]/div[2]/ytd-vertical-list-renderer/div[1]/ytd-video-renderer[1]/div[1]/div/div[1]/div/h3/a/yt-formatted-string')
Click.click()

In [62]:
video_comment2=[]

for _ in range(1000):
    driver.execute_script('window.scrollBy(0,5000)')

In [63]:
#Now will extract the 500 comment of the particular video

Comments=driver.find_elements(By.XPATH,'//div[@class="style-scope ytd-expander"]')
for i in Comments[1:501]:
    comm=i.text
    video_comment2.append(comm)

In [64]:
len(video_comment2)

500

In [65]:
Time=[]

Time1=driver.find_elements(By.XPATH,'//div[@id="header-author"]')
for a in Time1[1:501]:
    Time2=a.text.split('\n')[1]
    Time.append(Time2)

In [66]:
len(Time)

500

In [67]:
Upvote=[]

vote1=driver.find_elements(By.XPATH,'//div[@id="toolbar"]/span[2]')
for b in vote1[0:500]:
    Vote=b.text
    Upvote.append(Vote)

In [69]:
len(Upvote)

500

In [70]:
df4=pd.DataFrame({'Comment':video_comment2,'Upload dated':Time,'Upvote': Upvote})
df4

,Comment,Upload dated,Upvote
0,Jo part sabse badiya laga uska time stamp chod...,2 months ago,121K
1,Achanak Se Old Vibes Aagai,1 month ago,68K
2,Finally old Carry is back \nThis is the humour...,1 month ago (edited),4.2K
3,38.9 million subscriber is not a joke salute t...,8 hours ago,4.3K
4,I literally laughed throughout...you guy never...,4 weeks ago,7
...,...,...,...
495,0:38 \n1:18\nFav parts of all time ️\nAnd the ...,10 days ago,1
496,Notice he is wearing being human brand,2 months ago,
497,This guy never fails to impress us!️,1 month ago,252
498,Last wala big boss ki aawaj bahut hi bada funn...,1 month ago,1
499,Congratulations Ajay bhai for 39 million,7 days ago,

In [2]:
#Question No4 ----------------Flipkart('Oneplus Nord')

In [5]:
driver=webdriver.Chrome()
driver.get("https://www.flipkart.com/")

In [6]:
#lets input the smartphone name

input_Value=input("Enter the Smartphone Name : ")

Enter the Smartphone Name : Oneplus Nord

In [7]:
#lets search it

search_phone=driver.find_element(By.XPATH,'/html/body/div[1]/div/div[1]/div[1]/div[2]/div[2]/form/div/div/input')
search_phone.send_keys(input_Value)

search=driver.find_element(By.XPATH,'/html/body/div[1]/div/div[1]/div[1]/div[2]/div[2]/form/div/button')
search.click()

In [8]:
#lets scrape the brand name
Brand=[]

Phone_brand=driver.find_elements(By.XPATH,'//div[@class="_4rR01T"]')
for i in Phone_brand:
    brand=i.text.split(' ')[0]
    Brand.append(brand)

In [9]:
#lets scrape the Product model

Model=[]

Phone_model=driver.find_elements(By.XPATH,'//div[@class="_4rR01T"]')
for a in Phone_model:
    model=a.text.split('(')[0]
    Model.append(model)

In [10]:
#Lets scrape the Colour

Colour=[]

color=driver.find_elements(By.XPATH,'//div[@class="_4rR01T"]')
for b in color:
    colour=b.text.split('(')[1].split(',')[0]
    Colour.append(colour)

In [11]:
#Lets scrape the ROM-Storage
ROM=[]

Rom=driver.find_elements(By.XPATH,'//div[@class="_4rR01T"]')
for c in Rom:
    rom=c.text.split('(')[1].split(',')[1].split(')')[0]
    ROM.append(rom)

In [12]:
#lets scrape the price

Price=[]

pr=driver.find_elements(By.XPATH,'//div[@class="_30jeq3 _1_WHN1"]')
for d in pr:
    price=d.text
    Price.append(price)

In [13]:
#lets scrape the RAM

RAM=[]

Ram=driver.find_elements(By.XPATH,'//div[@class="fMghEO"]/ul[1]/li[1]')
for e in Ram:
    ram=e.text.split('|')[0]
    RAM.append(ram)

In [14]:
#Lets scrape the primary camera

Primary_Camera=[]

PC=driver.find_elements(By.XPATH,'//div[@class="fMghEO"]/ul[1]/li[3]')
for f in PC:
    brand=f.text.split('|')[0]
    Primary_Camera.append(brand)

In [15]:
#Lets scrape the battery

Battery=[]

Batt=driver.find_elements(By.XPATH,'//div[@class="fMghEO"]/ul[1]/li[4]')
for g in Batt:
    bat=g.text
    Battery.append(bat)

In [16]:
#lets scrape the Display details

Display=[]

disp=driver.find_elements(By.XPATH,'//div[@class="fMghEO"]/ul[1]/li[2]')
for h in disp:
    brand=h.text
    Display.append(brand)

In [18]:
df5=pd.DataFrame({'Brand':Brand,'Model Name': Model,'Colour': Colour,'RAM':RAM,'ROM':ROM,'Price':Price,'Primary camera':Primary_Camera,'Battery':Battery,'Display':Display})
df5

,Brand,Model Name,Colour,RAM,ROM,Price,Primary camera,Battery,Display
0,OnePlus,OnePlus Nord CE 2 Lite 5G,Blue Tide,6 GB RAM,128 GB,"₹17,818",64MP Rear Camera,5000 mAh Battery,16.74 cm (6.59 inch) Display
1,OnePlus,OnePlus Nord CE 2 Lite 5G,Black Dusk,6 GB RAM,128 GB,"₹17,737",64MP Rear Camera,5000 mAh Battery,16.74 cm (6.59 inch) Display
2,OnePlus,OnePlus Nord 3 5G,Misty Green,16 GB RAM,256 GB,"₹37,495",50MP Rear Camera,5000 mAh Battery,17.12 cm (6.74 inch) Display
3,OnePlus,OnePlus Nord 3 5G,Tempest Gray,16 GB RAM,256 GB,"₹37,284",50MP Rear Camera,5000 mAh Battery,17.12 cm (6.74 inch) Display
4,OnePlus,OnePlus Nord 3 5G,Misty Green,8 GB RAM,128 GB,"₹32,835",50MP Rear Camera,5000 mAh Battery,17.12 cm (6.74 inch) Display
5,OnePlus,OnePlus Nord 2T 5G,Jade Fog,8 GB RAM,128 GB,"₹28,295",50MP Rear Camera,4500 mAh Battery,17.02 cm (6.7 inch) Display
6,OnePlus,OnePlus NORD CE2 LITE 5G,Blue Tide,6 GB RAM,128 GB,"₹17,998",64MP Rear Camera,5000 mAh Battery,16.74 cm (6.59 inch) Display
7,OnePlus,OnePlus Nord 2T 5G,Gray Shadow,8 GB RAM,128 GB,"₹28,999",50MP Rear Camera,4500 mAh Battery,17.02 cm (6.7 inch) Display
8,OnePlus,OnePlus Nord 2T 5G,Jade Fog,8 GB RAM,128 GB,"₹27,999",50MP Rear Camera,4500 mAh Battery,17.02 cm (6.7 inch) Display
9,OnePlus,OnePlus Nord 2 5G,Blue Haze,12 GB RAM,256 GB,"₹34,990",50MP Rear Camera,4500 mAh Battery,16.33 cm (6.43 inch) Display
10,OnePlus,OnePlus Nord 3 5G,Tempest Gray,8 GB RAM,128 GB,"₹32,855",50MP Rear Camera,5000 mAh Battery,17.12 cm (6.74 inch) Display
11,OnePlus,OnePlus Nord 2 5G,PAC-MAN,12 GB RAM,256 GB,"₹37,999",50MP Rear Camera,4500 mAh Battery,16.33 cm (6.43 inch) Display
12,OnePlus,OnePlus Nord 2T 5G,Jade Fog,12 GB RAM,256 GB,"₹33,990",50MP Rear Camera,4500 mAh Battery,17.02 cm (6.7 inch) Display
13,OnePlus,OnePlus Nord CE 5G,Blue Void,8 GB RAM,128 GB,"₹24,499",64MP Rear Camera,4500 mAh Battery,16.33 cm (6.43 inch) Display
14,OnePlus,OnePlus Nord 2T 5G,Gray Shadow,8 GB RAM,128 GB,"₹28,990",50MP Rear Camera,4500 mAh Battery,17.02 cm (6.7 inch) Display
15,OnePlus,OnePlus Nord 2T 5G,Gray Shadow,8 GB RAM,128 GB,"₹28,988",50MP Rear Camera,4500 mAh Battery,17.02 cm (6.7 inch) Display
16,OnePlus,OnePlus Nord 2T 5G,Gray Shadow,8 GB RAM,128 GB,"₹27,930",50MP Rear Camera,4500 mAh Battery,17.02 cm (6.7 inch) Display
17,OnePlus,OnePlus Nord CE 3 Lite 5G,Chromatic Gray,8 GB RAM,256 GB,"₹21,249",108MP Rear Camera,5000 mAh Battery,17.07 cm (6.72 inch) Display
18,OnePlus,OnePlus Nord CE 3 Lite 5G,Pastel Lime,8 GB RAM,256 GB,"₹21,499",108MP Rear Camera,5000 mAh Battery,17.07 cm (6.72 inch) Display
19,OnePlus,OnePlus Nord CE 3 Lite 5G,Chromatic Gray,8 GB RAM,128 GB,"₹17,890",108MP Rear Camera,5000 mAh Battery,17.07 cm (6.72 inch) Display
20,OnePlus,OnePlus Nord,Gray Onyx,8 GB RAM,128 GB,"₹24,990",48MP + 8MP,4115 mAh Battery,16.36 cm (6.44 inch) Full HD+ Display
21,OnePlus,OnePlus Nord,Gray Onyx,6 GB RAM,64 GB,"₹22,689",48MP + 8MP,4115 mAh Battery,16.36 cm (6.44 inch) Full HD+ Display
22,OnePlus,OnePlus Nord CE 3 Lite 5G,Pastel Lime,8 GB RAM,128 GB,"₹18,999",108MP Rear Camera,5000 mAh Battery,17.07 cm (6.72 inch) Display
23,OnePlus,OnePlus Nord,Blue Marble,12 GB RAM,256 GB,"₹21,999",48MP + 8MP,4115 mAh Battery,16.36 cm (6.44 inch) Full HD+ Display

In [ ]:
csv_data1 = df5.to_csv(index=False)

print(csv_data1)

In [19]:
#Question No 9 -------Hostel London

In [21]:
driver=webdriver.Chrome()
driver.get('http://www.hostelworld.com/')

In [23]:
#lets search the loaction and search it

search_location=driver.find_element(By.XPATH,'/html/body/div[3]/div/div/div[2]/div[2]/div[2]/div/div/div/div[1]/div[1]/div/div[2]/input')
search_location.send_keys('London')

In [24]:
Click_location=driver.find_element(By.XPATH,'/html/body/div[3]/div/div/div[2]/div[2]/div[2]/div/div/div/div[1]/div[2]/div/ul/li[2]/button')
Click_location.click()

In [25]:
search_button=driver.find_element(By.XPATH,'/html/body/div[3]/div/div/div[2]/div[2]/div[2]/div/div/div/div[5]/button')
search_button.click()

In [26]:
#lets scrap the hostel URL 

HOSTEL_url=[]

url=driver.find_elements(By.XPATH,'//a[@class="property-card-container horizontal"]')
for i in url:
    HOSTEL_url.append(i.get_attribute('href'))

In [27]:
len(HOSTEL_url)

30

In [28]:
#lets Scrape the Hostel Name
Hostel_name=[]

for url in HOSTEL_url:
    driver.get(url)
    time.sleep(3)
    try:
        HN=driver.find_element(By.XPATH,'//div[@class="title-2"]')
        Hostel_name.append(HN.text)
    except NoSuchElementException:
        Hostel_name.append('-')

In [29]:
len(Hostel_name)

30

In [30]:
print(Hostel_name)

["Wombat's City Hostel London", 'Onefam Notting Hill by Hostel One', "St Christopher's Village", 'Generator London', 'Urbany Hostel London', 'Astor Hyde Park', 'Safestay London Elephant & Castle', 'Pickwick Hall', 'Phoenix Hostel', 'Safestay London Kensington Holland Park', 'Astor Museum Inn', 'No.8 Willesden Hostel London', 'London Backpackers', 'No.8 Seven Sisters', 'Queen Elizabeth Chelsea', 'Barmy Badger Backpackers', "St Christopher's Inn - London Bridge", 'Saint James Backpackers', 'Astor Victoria', "St Christopher's Hammersmith", "St Christopher's Greenwich", "St Christopher's Camden", 'PubLove @ The Steam Engine, Waterloo', 'Bell House Hostel', 'Astor Kensington', 'Smart Hyde Park View Hostel', "St Christopher's Shepherds Bush", 'Kabannas London St Pancras', 'Selina Camden', 'YHA London St Pauls']

In [31]:
#lets Scrape the Location/Address of hostel
Hostel_address=[]

for url in HOSTEL_url:
    driver.get(url)
    time.sleep(3)
    try:
        HA=driver.find_element(By.XPATH,'//button[@class="property-address"]')
        Hostel_address.append(HA.text)
    except NoSuchElementException:
        Hostel_address.append('-')
        
        
        
        
#lets Scrape the description
Description=[]

for url in HOSTEL_url:
    driver.get(url)
    time.sleep(3)
    try:
        Desc=driver.find_element(By.XPATH,'//div[@class="description-container"]/div[1]/div[2]')
        Description.append(Desc.text)
    except NoSuchElementException:
        Description.append('-')       
        

        
#lets Scrape the Rating
Rating=[]

for url in HOSTEL_url:
    driver.get(url)
    time.sleep(3)
    try:
        rate=driver.find_element(By.XPATH,'//div[@class="flex-20"]/div[1]/div[1]')
        Rating.append(rate.text)
    except NoSuchElementException:
        Rating.append('-')
        
        
        
#Lets Scrape the overall Rating       
Overall_rating=[]

for url in HOSTEL_url:
    driver.get(url)
    time.sleep(3)
    try:
        overall=driver.find_element(By.XPATH,'//div[@class="flex-20"]/div[1]/div[2]/div[1]/span[1]')
        Overall_rating.append(overall.text)
    except NoSuchElementException:
        Overall_rating.append('-')
        
        
        
#Lets scrape the Total review

Total_review=[]

for url in HOSTEL_url:
    driver.get(url)
    time.sleep(3)
    try:
        total=driver.find_element(By.XPATH,'//div[@class="flex-20"]/div[1]/div[2]/div[2]')
        Total_review.append(total.text.split(' ')[0])
    except NoSuchElementException:
        Total_review.append('-')
        
        
        
        
        
#lets scrape the private room price

Private=[]


for url in HOSTEL_url:
    driver.get(url)
    time.sleep(3)
    try:
        private=driver.find_element(By.XPATH,'//div[@class="rate-container bordered"]/div[1]/div[2]/div[1]')
        Private.append(private.text)
    except NoSuchElementException:
        Private.append('-')

In [32]:
len(Hostel_address)
len(Description)
len(Rating)
len(Overall_rating)
len(Total_review)
len(Private)

30

In [33]:
df6=pd.DataFrame({'Hostel Name':Hostel_name,'Hostel address': Hostel_address,'Hostel Description': Description,'Hostel rating': Rating,'Overall Rating': Overall_rating,'Total review':Total_review,'Private room price':Private})
df6

,Hostel Name,Hostel address,Hostel Description,Hostel rating,Overall Rating,Total review,Private room price
0,Wombat's City Hostel London,"7 Dock Street,",A safe haven in the middle of the metropolis: ...,9.0,Superb,15136,Rs19579.73
1,Onefam Notting Hill by Hostel One,"63 Prince's Square,",The perfect place for solo travelers to connec...,9.7,Superb,2170,Standard
2,St Christopher's Village,"165 Borough High Street,",Hostelworld visitors have said St Christopher'...,8.1,Fabulous,12297,Rs3197.66
3,Generator London,"Compton Place, Off 37 Tavistock Place, WC1,",Hostelworld guests have said Generator Hostel ...,7.6,Very Good,7631,Standard
4,Urbany Hostel London,"48-49 Princes Square, Paddington,","Welcome to Urbany Hostel London, our first int...",9.5,Superb,849,Standard
5,Astor Hyde Park,"191 Queensgate, South Kensington,",Note: 18-40 yrs old only. Astor Hyde Park won ...,8.3,Fabulous,12133,Standard
6,Safestay London Elephant & Castle,"144-152 Walworth Road,",Safestay at Elephant and Castle is located in ...,7.2,Very Good,5039,-
7,Pickwick Hall,"7 Bedford Place, Bloomsbury,",Pickwick Hall provides accommodation for touri...,8.7,Fabulous,2691,-
8,Phoenix Hostel,"6 Daventry Street,","The Phoenix Bar & Hostel, housed in a homely E...",8.0,Fabulous,4315,Rs2641.32
9,Safestay London Kensington Holland Park,"Holland Park Ave, Holland Walk,",Safestay Holland Park\n\nSafestay Holland Park...,6.9,Good,1604,-
10,Astor Museum Inn,"27 Montague Street, Bloomsbury,",Note: 18-40 yrs old only. Astor Museum won 1st...,8.2,Fabulous,9298,Standard
11,No.8 Willesden Hostel London,"305 High Rd, Willesden,",At No.8 we take pride in our Customer Service ...,6.5,Good,5055,-
12,London Backpackers,"8/10 Queens Parade, Queens Road, Hendon Central,",IMPORTANT NOTICE: \n\nThis hostel is for 18 - ...,7.6,Very Good,4493,Standard
13,No.8 Seven Sisters,"618 Seven Sisters Rd, Seven Sisters,","For Great Facilities, Comfort & Affordability ...",5.2,Rating,4040,-
14,Queen Elizabeth Chelsea,"58 Bagleys Lane,",PLEASE NOTE WE ONLY ACCEPT GUESTS FROM THE AGE...,7.3,Very Good,3534,Standard
15,Barmy Badger Backpackers,"17 Longridge Road, Earls Court,",The Badger is unique for London in that we hav...,9.0,Superb,1955,-
16,St Christopher's Inn - London Bridge,"121 Borough High Street,",St Christopher's Inn - London Bridge is all ab...,7.8,Very Good,3528,Rs3043.53
17,Saint James Backpackers,"21 Longridge Road,","Saint James Backpackers, set in a classic Vict...",7.7,Very Good,1909,Standard
18,Astor Victoria,"73 Belgrave Road, Victoria,",Note: 18-40 yrs old only. Astor Victoria won 1...,7.1,Very Good,14998,Standard
19,St Christopher's Hammersmith,"28, Hammersmith Broadway, Hammersmith,","The friendly, attentive and welcoming staff of...",7.4,Very Good,4273,Rs2541.03
20,St Christopher's Greenwich,"189 Greenwich High Road, Greenwich,",St Christopher's Greenwich is 'ideally located...,7.8,Very Good,3373,Rs2462.91
21,St Christopher's Camden,"48-50 Camden High Street, Camden NW1,",If you're looking to explore the markets and m...,7.0,Very Good,4066,Rs2695.16
22,"PubLove @ The Steam Engine, Waterloo","41-42 Cosser St,","The Steam Engine, Bestplace Inn is a great hos...",8.0,Fabulous,409,-
23,Bell House Hostel,"91 Bell St, Bell House,","Boasting a bar and a shared lounge, Bell House...",7.6,Very Good,80,Standard
24,Astor Kensington,"45 Queensborough Terrace, Bayswater,",Note: 18-40 yrs old only. Astor Kensington won...,7.8,Very Good,6519,Standard
25,Smart Hyde Park View Hostel,"16 Leinster Terrace W2 3EU,","Smart Hyde Park View is a 'clean, pleasant pla...",7.8,Very Good,4709,-
26,St Christopher's Shepherds Bush,"Belushis Bar, 13-15 Shepherds Bush Green.,",St Christopher's Shepherds Bush has been highl...,7.1,Very Good,785,Rs2432.29
27,Kabannas London St Pancras,"79-81 Euston Road,",Kabannas London St Pancras has friendly recept...,9.1,Superb,2872,-
28,Selina Camden,"89 Chalk Farm Rd, Chalk Farm,","Among underground music venues, innovative mus...",8.7,Fabulous,54,Standard
29,YHA London St Pauls,"36 Carter Lane, EC4V 5AB,",If your main interest in London is museums and...,8.8,Fabulous,2089,-